## Phoenix Telemetry Edge (PTE) Demo Values
## A minimal configuration for quick-start

image:
  repository: ghcr.io/deepaucksharma-nr/pte-collector
  tag: v0.1.0

# Replace with the actual secret name containing your New Relic License Key
newRelicLicenseKeySecretName: "nr-license-key"

# Basic sampling configuration
sampling:
  head:
    initialProbability: 0.3
  tail_reservoir:
    k_size: 2000

# Simple PII protection
pii:
  fieldsToHash: ["user.email"]
  defaultSaltSecret:
    name: "pte-pii-salts"
    key: "DEFAULT_PII_SALT"

# Enable persistence
persistence:
  enabled: true
  size: 2Gi

# Reduce resource requirements for testing
collector:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi