## Phoenix Telemetry Edge (PTE) Demo Values
## A minimal configuration for quick-start

image:
  repository: ghcr.io/deepaucksharma-nr/pte-collector
  tag: v0.1.0

# Replace with the actual secret name containing your New Relic License Key
newRelicLicenseKeySecretName: "nr-license-key"

# Basic sampling configuration
sampling:
  head:
    initialProbability: 0.3
    minProbability: 0.01
    maxProbability: 0.9
    logs:
      enabled: false
      initialProbability: 0.5
      minProbability: 0.01
      maxProbability: 0.9
      recordIDFields: ["log.file.path", "k8s.pod.name", "message"]
  tail_reservoir:
    k_size: 2000
    windowSeconds: 60
    checkpointIntervalSeconds: 10
  adaptive_controller:
    enabled: true
    intervalSeconds: 15
    targetQueueUtilizationHigh: 0.8
    targetQueueUtilizationLow: 0.2
    adjustmentFactorUp: 1.25
    adjustmentFactorDown: 0.8
    ewmaAlpha: 0.3
    aggressiveDropFactor: 0.5
    aggressiveDropWindowCount: 3

# Process metrics filtering
processMetrics:
  enabled: false
  topN: 50
  cpuThreshold: 0.5
  memoryThreshold: 0.5
  idleWindowSeconds: 300
  maxPidsToScanPerScrape: 5000

  # Fallback parser configuration
  fallbackParser:
    enabled: true
    attributesToFetch: ["command_line", "owner", "io"]

  # Attribute presence gate
  attrPresenceGate:
    strictMode: false
    criticalAttributes: ["process.executable.name", "process.command_line"]

# Simple PII protection
pii:
  fieldsToHash: ["user.email"]
  defaultSaltSecret:
    name: "pte-pii-salts"
    key: "DEFAULT_PII_SALT"
  # Uncomment if using external PII rules
  # rulesCsvConfigMapName: "pte-pii-rules"

# Enable persistence
persistence:
  enabled: true
  size: 2Gi

# Reduce resource requirements for testing
collector:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# Multi-tenant configuration (disabled by default)
multiTenant:
  enabled: false
  # Example tenant config commented out
  # tenants:
  # - id: "tenant1"
  #   name: "Tenant 1"
  #   licenseKeySecretName: "tenant1-license-key"

# Monitoring configuration
monitoring:
  prometheus:
    enabled: true
    port: 8888
  health:
    enabled: true
    port: 13133
  zpages:
    enabled: true
    port: 55679